using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json.Linq;

namespace OverlayPluginAddon
{
    public enum SpeedAttribute
    {
        /// <summary>The recast is a flat number no matter how much speed the player has (dance steps).</summary>
        None,
        SkillSpeed,
        SpellSpeed,
    }

    public class ActionDef
    {
        public uint Id;
        public string Name;

        /// <summary>Milliseconds the action occupies the GCD.</summary>
        public int Recast;

        /// <summary>Cast time in milliseconds, only recorded when it is at least a full GCD.</summary>
        public int CastTime;

        public SpeedAttribute SpeedAttribute;
    }

    /// <summary>
    /// Per-action GCD recast data, generated by tools/Build-ActionData.js from xivanalysis.
    ///
    /// This is the one part of the GCD calculation that cannot be observed: FFXIV_ACT_Plugin's
    /// resources say which actions are GCDs but not how long they occupy it, and xivanalysis
    /// maintains that by hand. Anything absent from the table is a plain 2.5s GCD that scales
    /// with the player's speed stat, which is the overwhelming majority.
    /// </summary>
    public class ActionData
    {
        public const int BaseGcdMs = 2500;

        /// <summary>
        /// Extra delay before the next GCD when a cast is at least a full GCD long - "caster tax".
        /// Matches ANIMATION_LOCK in xivanalysis.
        /// </summary>
        public const int AnimationLockMs = 100;

        private readonly Dictionary<uint, ActionDef> byId = new Dictionary<uint, ActionDef>();
        private readonly Dictionary<uint, double> speedStatuses = new Dictionary<uint, double>();

        /// <summary>
        /// For a haste status that only quickens some actions, the ids it applies to. Inspiration
        /// hastens a Pictomancer's aetherhue spells and Star Prism and nothing else, and the
        /// hammer combo pressed inside Starry Muse must not inherit its 0.75.
        /// </summary>
        private readonly Dictionary<uint, HashSet<uint>> speedStatusLimits = new Dictionary<uint, HashSet<uint>>();

        public string LoadError { get; private set; }
        public int ActionCount => byId.Count;
        public int SpeedStatusCount => speedStatuses.Count;

        /// <summary>
        /// Every action xivanalysis flags as rolling the GCD, whatever FFXIV's own category says.
        ///
        /// The category table files a Ninja's mudras and every Ninjutsu under 4, "Ability" - and it
        /// is right that they are not weaponskills - yet Ten, Chi, Raiton are 0.5s + 0.5s + 1.5s of
        /// GCD. Asking the category alone left that whole stretch reading as a gap after Aeolian
        /// Edge, charged as lost time on every single Ninjutsu, and a Ninja's uptime collapsed by
        /// several points a minute. Monk's meditations and Samurai's Meditate are the same case.
        /// A scan of every job found nothing the category calls a GCD that xivanalysis says is not,
        /// so this list decides first and the category decides the rest.
        /// </summary>
        private readonly HashSet<uint> onGcd = new HashSet<uint>();

        public int OnGcdCount => onGcd.Count;

        /// <summary>Whether xivanalysis says the action rolls the GCD. False also for an id it does not list.</summary>
        public bool IsOnGcd(uint actionId) => onGcd.Contains(actionId);

        /// <summary>The default every action not in the table follows.</summary>
        private static readonly ActionDef Default = new ActionDef
        {
            Recast = BaseGcdMs,
            SpeedAttribute = SpeedAttribute.SkillSpeed,
        };

        public ActionDef Get(uint actionId) =>
            byId.TryGetValue(actionId, out var def) ? def : Default;

        /// <summary>Whether the table has a real entry, or <see cref="Get"/> fell back to the default.</summary>
        public bool Knows(uint actionId) => byId.ContainsKey(actionId);

        /// <summary>
        /// Haste multiplier one status applies to one action: 1 when the status does not affect
        /// speed, or affects speed but not this action.
        /// </summary>
        public double SpeedModifierOf(uint statusId, uint actionId)
        {
            if (!speedStatuses.TryGetValue(statusId, out var modifier)) return 1.0;
            if (speedStatusLimits.TryGetValue(statusId, out var only) && !only.Contains(actionId)) return 1.0;
            return modifier;
        }

        public bool IsSpeedStatus(uint statusId) => speedStatuses.ContainsKey(statusId);

        public static ActionData Load(string path)
        {
            var data = new ActionData();

            try
            {
                if (!File.Exists(path))
                {
                    data.LoadError = "actions.json not found at " + path;
                    return data;
                }

                var root = JObject.Parse(File.ReadAllText(path));

                foreach (var entry in root["actions"] ?? new JArray())
                {
                    var id = (uint?)entry["id"];
                    if (id == null) continue;

                    data.byId[id.Value] = new ActionDef
                    {
                        Id = id.Value,
                        Name = (string)entry["name"] ?? "",
                        Recast = (int?)entry["recast"] ?? BaseGcdMs,
                        CastTime = (int?)entry["castTime"] ?? 0,
                        SpeedAttribute = ParseAttribute((string)entry["speedAttribute"]),
                    };
                }

                foreach (var entry in root["speedStatuses"] ?? new JArray())
                {
                    var id = (uint?)entry["id"];
                    var modifier = (double?)entry["speedModifier"];
                    if (id == null || modifier == null || modifier <= 0) continue;

                    data.speedStatuses[id.Value] = modifier.Value;

                    if (entry["limitedTo"] is JArray only && only.Count > 0)
                    {
                        var set = new HashSet<uint>();
                        foreach (var a in only)
                        {
                            var actionId = (uint?)a;
                            if (actionId != null) set.Add(actionId.Value);
                        }
                        data.speedStatusLimits[id.Value] = set;
                    }
                }

                foreach (var entry in root["onGcd"] ?? new JArray())
                {
                    var id = (uint?)entry;
                    if (id != null) data.onGcd.Add(id.Value);
                }
            }
            catch (Exception ex)
            {
                data.LoadError = ex.Message;
            }

            return data;
        }

        private static SpeedAttribute ParseAttribute(string attribute)
        {
            switch (attribute)
            {
                case "SKILL_SPEED": return SpeedAttribute.SkillSpeed;
                case "SPELL_SPEED": return SpeedAttribute.SpellSpeed;
                default: return SpeedAttribute.None;
            }
        }

        // ------------------------------------------------------------------ the speed formula
        //
        // Straight from xivanalysis' speedStatMapper, which in turn matches Allagan Studies.
        // Kept here rather than in the tracker because both directions are needed: observed
        // intervals go one way to a stat, and the stat comes back the other way as the recast of
        // every action the player has, including ones whose base recast is not 2.5s.

        private const int SubAttributeMinimum = 420;
        private const int StatDivisor = 2780;

        /// <summary>Turns an observed GCD length in milliseconds into the speed stat that produces it.</summary>
        public static int SpeedStatFor(double observedGcdMs)
        {
            return (int)Math.Floor(1.0 / 130 * StatDivisor * (1000 - 1000 * observedGcdMs / BaseGcdMs)) + SubAttributeMinimum;
        }

        /// <summary>Applies a speed stat to a base duration, in milliseconds.</summary>
        public static double AdjustedDuration(int speedStat, double baseDurationMs)
        {
            var attributeMultiplier = 1000 - Math.Floor(130.0 * (speedStat - SubAttributeMinimum) / StatDivisor);
            var adjusted = Math.Floor(attributeMultiplier * baseDurationMs / 1000);

            // The haste and astral/umbral terms of the real formula are folded in by the caller as
            // a plain multiplier, so the remaining two floors reduce to centiseconds.
            return Math.Floor(adjusted / 10) * 10;
        }
    }
}
